<?php
/**
 * ConnectionStatisticsDTO
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Tequila API
 *
 * The purpose of this documentation is to provide developers an insight of how to interact with Mysterium Node via Tequila API. This should demonstrate all the possible API calls with described parameters and responses.
 *
 * The version of the OpenAPI document: dev
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ConnectionStatisticsDTO Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ConnectionStatisticsDTO implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ConnectionStatisticsDTO';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'bytes_received' => 'int',
        'bytes_sent' => 'int',
        'duration' => 'int',
        'spent_tokens' => '\OpenAPI\Client\Model\Tokens',
        'throughput_received' => 'int',
        'throughput_sent' => 'int',
        'tokens_spent' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'bytes_received' => 'uint64',
        'bytes_sent' => 'uint64',
        'duration' => 'int64',
        'spent_tokens' => null,
        'throughput_received' => 'uint64',
        'throughput_sent' => 'uint64',
        'tokens_spent' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'bytes_received' => false,
        'bytes_sent' => false,
        'duration' => false,
        'spent_tokens' => false,
        'throughput_received' => false,
        'throughput_sent' => false,
        'tokens_spent' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'bytes_received' => 'bytes_received',
        'bytes_sent' => 'bytes_sent',
        'duration' => 'duration',
        'spent_tokens' => 'spent_tokens',
        'throughput_received' => 'throughput_received',
        'throughput_sent' => 'throughput_sent',
        'tokens_spent' => 'tokens_spent'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'bytes_received' => 'setBytesReceived',
        'bytes_sent' => 'setBytesSent',
        'duration' => 'setDuration',
        'spent_tokens' => 'setSpentTokens',
        'throughput_received' => 'setThroughputReceived',
        'throughput_sent' => 'setThroughputSent',
        'tokens_spent' => 'setTokensSpent'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'bytes_received' => 'getBytesReceived',
        'bytes_sent' => 'getBytesSent',
        'duration' => 'getDuration',
        'spent_tokens' => 'getSpentTokens',
        'throughput_received' => 'getThroughputReceived',
        'throughput_sent' => 'getThroughputSent',
        'tokens_spent' => 'getTokensSpent'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('bytes_received', $data ?? [], null);
        $this->setIfExists('bytes_sent', $data ?? [], null);
        $this->setIfExists('duration', $data ?? [], null);
        $this->setIfExists('spent_tokens', $data ?? [], null);
        $this->setIfExists('throughput_received', $data ?? [], null);
        $this->setIfExists('throughput_sent', $data ?? [], null);
        $this->setIfExists('tokens_spent', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets bytes_received
     *
     * @return int|null
     */
    public function getBytesReceived()
    {
        return $this->container['bytes_received'];
    }

    /**
     * Sets bytes_received
     *
     * @param int|null $bytes_received bytes_received
     *
     * @return self
     */
    public function setBytesReceived($bytes_received)
    {
        if (is_null($bytes_received)) {
            throw new \InvalidArgumentException('non-nullable bytes_received cannot be null');
        }
        $this->container['bytes_received'] = $bytes_received;

        return $this;
    }

    /**
     * Gets bytes_sent
     *
     * @return int|null
     */
    public function getBytesSent()
    {
        return $this->container['bytes_sent'];
    }

    /**
     * Sets bytes_sent
     *
     * @param int|null $bytes_sent bytes_sent
     *
     * @return self
     */
    public function setBytesSent($bytes_sent)
    {
        if (is_null($bytes_sent)) {
            throw new \InvalidArgumentException('non-nullable bytes_sent cannot be null');
        }
        $this->container['bytes_sent'] = $bytes_sent;

        return $this;
    }

    /**
     * Gets duration
     *
     * @return int|null
     */
    public function getDuration()
    {
        return $this->container['duration'];
    }

    /**
     * Sets duration
     *
     * @param int|null $duration connection duration in seconds
     *
     * @return self
     */
    public function setDuration($duration)
    {
        if (is_null($duration)) {
            throw new \InvalidArgumentException('non-nullable duration cannot be null');
        }
        $this->container['duration'] = $duration;

        return $this;
    }

    /**
     * Gets spent_tokens
     *
     * @return \OpenAPI\Client\Model\Tokens|null
     */
    public function getSpentTokens()
    {
        return $this->container['spent_tokens'];
    }

    /**
     * Sets spent_tokens
     *
     * @param \OpenAPI\Client\Model\Tokens|null $spent_tokens spent_tokens
     *
     * @return self
     */
    public function setSpentTokens($spent_tokens)
    {
        if (is_null($spent_tokens)) {
            throw new \InvalidArgumentException('non-nullable spent_tokens cannot be null');
        }
        $this->container['spent_tokens'] = $spent_tokens;

        return $this;
    }

    /**
     * Gets throughput_received
     *
     * @return int|null
     */
    public function getThroughputReceived()
    {
        return $this->container['throughput_received'];
    }

    /**
     * Sets throughput_received
     *
     * @param int|null $throughput_received Download speed in bits per second
     *
     * @return self
     */
    public function setThroughputReceived($throughput_received)
    {
        if (is_null($throughput_received)) {
            throw new \InvalidArgumentException('non-nullable throughput_received cannot be null');
        }
        $this->container['throughput_received'] = $throughput_received;

        return $this;
    }

    /**
     * Gets throughput_sent
     *
     * @return int|null
     */
    public function getThroughputSent()
    {
        return $this->container['throughput_sent'];
    }

    /**
     * Sets throughput_sent
     *
     * @param int|null $throughput_sent Upload speed in bits per second
     *
     * @return self
     */
    public function setThroughputSent($throughput_sent)
    {
        if (is_null($throughput_sent)) {
            throw new \InvalidArgumentException('non-nullable throughput_sent cannot be null');
        }
        $this->container['throughput_sent'] = $throughput_sent;

        return $this;
    }

    /**
     * Gets tokens_spent
     *
     * @return string|null
     */
    public function getTokensSpent()
    {
        return $this->container['tokens_spent'];
    }

    /**
     * Sets tokens_spent
     *
     * @param string|null $tokens_spent tokens_spent
     *
     * @return self
     */
    public function setTokensSpent($tokens_spent)
    {
        if (is_null($tokens_spent)) {
            throw new \InvalidArgumentException('non-nullable tokens_spent cannot be null');
        }
        $this->container['tokens_spent'] = $tokens_spent;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


